// PL lang variables

tinyMCE.addToLang('',{
bold_desc : 'Pogrubienie',
italic_desc : 'Kursywa',
underline_desc : 'Podkreœlenie',
striketrough_desc : 'Przekreœlenie',
justifyleft_desc : 'Otaczanie z lewej',
justifycenter_desc : 'Wyœrodkowanie',
justifyright_desc : 'Otaczanie z prawej',
justifyfull_desc : 'Justowanie',
bullist_desc : 'Lista nie numerowana',
numlist_desc : 'Lista numerowana',
outdent_desc : 'Zmniejsz wciêcie',
indent_desc : 'Zwieksz wciêcie',
undo_desc : 'Cofnij',
redo_desc : 'Ponów',
link_desc : 'Wstaw/Edytuj link',
unlink_desc : 'Skasuj link',
image_desc : 'Wstaw/Edytuj obrazek',
cleanup_desc : 'Wyczyœæ niepotrzebny kod',
focus_alert : 'Musisz zaznaczyæ cokolwiek przed u¿yciem tej komendy.',
edit_confirm : 'Czy chcesz u¿yc edytora WYSIWIG dla tego pola ?',
insert_link_title : 'Wstaw/Edytuj Link',
insert : 'Wstaw',
update : 'Zmieñ',
cancel : 'WyjdŸ',
insert_link_url : 'Adres URL',
insert_link_target : 'Cel',
insert_link_target_same : 'Otwórz w tym samym oknie',
insert_link_target_blank : 'Otwórz w nowym oknie',
insert_image_title : 'Wstaw/Edytuj obrazek',
insert_image_src : 'Adres URL obrazka',
insert_image_alt : 'Opis obrazka',
help_desc : 'Pomoc',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Kopiowanie/Wycinanie/Wklejanie nie jest obslugiwane w przegladarkach Mozilla and Firefox.\nPotrzebujesz wiecej informacji na ten temat?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
