// PL lang variables

tinyMCE.addToLang('',{
table_desc : 'Wstaw now¹ tabelê',
table_insert_row_before_desc : 'Wstaw wiersz przed',
table_insert_row_after_desc : 'Wstaw wiersz po',
table_delete_row_desc : 'Skasuj wiersz',
table_insert_col_before_desc : 'Wstaw kolumnê przed',
table_insert_col_after_desc : 'Wstaw kolumnê po',
table_delete_col_desc : 'Skasuj kolumnê',
insert_table_title : 'Wstaw/Modyfikuj tabelê',
insert_table_width : 'Szerokoœæ',
insert_table_height : 'Wysokoœæ',
insert_table_cols : 'Kolumny',
insert_table_rows : 'Wiersze',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Ramka',
insert_table_align : 'Wyrównanie',
insert_table_align_default : 'Domyœlny',
insert_table_align_left : 'Do lewej',
insert_table_align_right : 'Do prawej',
insert_table_align_middle : 'Wycentrowanie',
insert_table_class : 'Klasa',
table_row_title : 'W³aœciwoœci wiersza',
table_cell_title : 'W³aœciwoœci komórki',
table_row_desc : 'W³aœciwoœci wiersza',
table_cell_desc : 'W³aœciwoœci komórki',
insert_table_valign : 'Wyrównanie pionowe',
insert_table_align_top : 'do góry',
insert_table_align_bottom : 'do do³u',
table_props_desc : 'W³aœciwosci tabeli',
table_merge_cells_title : 'Z³¹cz komórki tabeli',
table_split_cells_desc : 'Podziel komórki tabeli',
table_merge_cells_desc : 'Z³¹cz komórki tabeli',
table_cut_row_desc : 'Wytnik wiersz tabeli',
table_copy_row_desc : 'Kopiuj wiersz ',
table_paste_row_before_desc : 'Wstaw wiersz tabeli przed',
table_paste_row_after_desc : 'Wstaw wiersz tabeli po',
table_insert_desc : 'Wstaw now¹ tabelê'
});
